
version: '3.8'
services:
  activemq:
    image: apache/activemq-classic:5.18.3
    container_name: insight_activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: insightdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
      - postgres

  project-service:
    build: ./project-service
    ports:
      - "8083:8083"
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
      - postgres

  finance-service:
    build: ./finance-service
    ports:
      - "8084:8084"
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/insightdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - activemq
      - postgres

  notification-service:
    build: ./notification-service
    ports:
      - "8085:8085"
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
