
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    static_configs:
      - targets: ['user-service:8082','project-service:8083','finance-service:8084','notification-service:8085','auth-service:8086']
